
import { ActivityLog, SessionMetrics } from '../types';
import { UserProfile } from '../services/persistence';

export const downloadFile = (content: string, filename: string, type: string) => {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const exportData = (
  format: 'json' | 'csv' | 'md',
  logs: ActivityLog[],
  profile: UserProfile | null,
  currentMetrics: SessionMetrics
) => {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const dateStr = new Date().toLocaleString();

  if (format === 'json') {
    const fullData = {
      meta: {
        exportDate: new Date().toISOString(),
        system: "SENTINEL // CORE",
        version: "3.1.0"
      },
      profile,
      currentSession: currentMetrics,
      activityLogs: logs
    };
    downloadFile(JSON.stringify(fullData, null, 2), `sentinel-dump-${timestamp}.json`, 'application/json');
    
  } else if (format === 'csv') {
    // CSV primarily for Activity Logs
    const headers = ['Timestamp', 'Activity', 'FocusLevel', 'RiskScore', 'TrustScore', 'Description'];
    const rows = logs.map(log => [
      new Date(log.timestamp).toISOString(),
      `"${log.activity.replace(/"/g, '""')}"`,
      log.focusLevel,
      log.riskScore,
      log.trustScore,
      `"${log.description.replace(/"/g, '""')}"`
    ]);
    
    const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    downloadFile(csvContent, `sentinel-logs-${timestamp}.csv`, 'text/csv');

  } else if (format === 'md') {
    // Markdown Incident Report
    let md = `# SENTINEL // CORE - INCIDENT REPORT\n`;
    md += `**Date Generated:** ${dateStr}\n`;
    md += `**System Status:** ${currentMetrics.privacyModeEnabled ? 'PRIVACY MODE' : 'STANDARD MONITORING'}\n\n`;
    
    md += `## BIOMETRIC PROFILE STATUS\n`;
    if (profile) {
      md += `- **Known WPM:** ${profile.avgWpm}\n`;
      md += `- **Known Flight Time:** ${profile.avgFlightTime}ms\n`;
      md += `- **Sessions Logged:** ${profile.totalSessions}\n`;
    } else {
      md += `*No historical profile established.*\n`;
    }
    md += `\n`;

    md += `## CURRENT SESSION METRICS\n`;
    md += `- **Avg Speed:** ${Math.round(currentMetrics.wpm)} WPM\n`;
    md += `- **Rhythm Variance:** ${currentMetrics.rhythmVariance.toFixed(2)}ms\n`;
    md += `- **Mouse Velocity:** ${currentMetrics.mouseMetrics.avgVelocity.toFixed(2)} px/ms\n`;
    md += `- **Bot Detected:** ${currentMetrics.rhythmVariance < 5 ? 'YES (Synthetic Patterns)' : 'NO'}\n\n`;

    md += `## ACTIVITY LOGS (Recent)\n`;
    md += `| Time | Activity | Risk | Trust | Focus |\n`;
    md += `|---|---|---|---|---|\n`;
    
    logs.slice(0, 20).forEach(log => {
        const time = new Date(log.timestamp).toLocaleTimeString();
        md += `| ${time} | ${log.activity} | ${log.riskScore} | ${log.trustScore} | ${log.focusLevel} |\n`;
    });
    
    md += `\n\n*Generated by SENTINEL // CORE Biometric Security Framework*`;

    downloadFile(md, `sentinel-report-${timestamp}.md`, 'text/markdown');
  }
};
